#!/usr/bin/env bash
#
# Sets up requirements to provision with ansible
#

#
# Clean display function
#
# usage:
#        display "My thing to output"
#
function display() {
    echo "----> $1"
}

# if [ ! `which pip` ]
# then
#     display "Installing pip"
#     sudo easy_install pip
# fi

# sudo pip install --upgrade -r requirements.txt

if [ ! `which brew` ]; then
    display "Installing Homebrew"
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

if [ `which brew` ]; then
    brew install python3
    pip3 install --upgrade pip
    pip3 install --upgrade requirements
fi

if [ ! -d "${HOME}/venv" ]; then
    mkdir ~/venv
fi

python3 -m venv ~/venv/general

# vim: ft=sh: