---

- name: Install brew packages
  homebrew:
    name: "{{ langs_brew_packages }}"
    state: latest
  tags:
    - langs
    - brew

# - name: Install brew packages
#   homebrew:
#     name: "{{ item.name }}"
#     install_options: "{{ item.install_options | default('') }}"
#     state: latest
#   with_items: "{{ langs_brew_packages_options }}"
#   tags:
#     - langs
#     - brew

- name: Install erlang brew packages
  homebrew:
    name: "{{ erlang_brew_packages }}"
    state: latest
  tags:
    - langs
    - erlang
    - brew

- name: Install lang cask applications
  command: "brew cask install {{item.install_options | default('') }} {{ item.name }}"
  with_items: "{{ langs_brew_casks }}"
  ignore_errors: True
  tags:
    - langs
    - brew
    - brew-cask
