---

python_brew_packages:
  - name: python3

python_packages:
  - ansible
  - ansible-lint
  - autopep8
  - awscli
  - boto
  - flake8
  - neovim
  - pip
  - pipenv
  - pylint
  - pylint
  - virtualenv
  - virtualenvwrapper
python_pyenv_install_cmd: "CFLAGS=\"-I$(brew --prefix openssl)/include -I$(xcrun --show-sdk-path)/usr/include\" LDFLAGS=\"-L$(brew --prefix openssl)/lib -L/usr/local/opt/sqlite/lib\" pyenv install"
python_use_pyenv: True
python_pyenv_versions:
  - 3.3.6
  - 3.5.1
