;;
;; Wombat theme ported from Vim
;;

; NOTE: Use this method instead of regular (set-background-color "#foo")
; so that the properties propegate to all new frames
(setq default-frame-alist
	(append default-frame-alist
	'((background-color . "#242424")
	  (foreground-color . "#f6f3e8")
	  (cursor-color . "#656565")
      (face-foreground 'font-lock-comment-face "#99968b")
      (face-italic-p 'font-lock-comment-face t)
      (face-foreground 'font-lock-doc-face "#99968b")
      (face-italic-p 'font-lock-doc-face t)
      (face-foreground 'font-lock-constant-face "#e5786d")
      (face-foreground 'font-lock-string-face "#95e454")
      (face-italic-p 'font-lock-string-face t)
      (face-foreground 'font-lock-variable-name-face "#cae682")
      (face-foreground 'font-lock-function-name-face "#cae682")
      (face-foreground 'font-lock-type-face "#cae682")
      (face-foreground 'font-lock-builtin-face "#8ac6f2")
      (face-foreground 'font-lock-keyword-face "#8ac6f2")
      (face-foreground 'font-lock-preprocessor-face "#e5786d")
      (face-foreground 'font-lock-negation-char-face "#e7f6da")
      (face-foreground 'link "#8ac6f2")
      (face-bold-p 'link t)
      (face-underline-p 'link t)
      (face-foreground 'region "#f6f3e8")
      (face-background 'region "#444444")
      (face-foreground 'lazy-highlight "black")
      (face-background 'lazy-highlight "yellow")
)))

;(set-background-color "#242424")
;(set-foreground-color "#f6f3e8")
;(set-cursor-color "#656565")
;(set-face-foreground 'font-lock-comment-face "#99968b")
;(set-face-italic-p 'font-lock-comment-face t)
;(set-face-foreground 'font-lock-doc-face "#99968b")
;(set-face-italic-p 'font-lock-doc-face t)
;(set-face-foreground 'font-lock-constant-face "#e5786d")
;(set-face-foreground 'font-lock-string-face "#95e454")
;(set-face-italic-p 'font-lock-string-face t)
;(set-face-foreground 'font-lock-variable-name-face "#cae682")
;(set-face-foreground 'font-lock-function-name-face "#cae682")
;(set-face-foreground 'font-lock-type-face "#cae682")
;(set-face-foreground 'font-lock-builtin-face "#8ac6f2")
;(set-face-foreground 'font-lock-keyword-face "#8ac6f2")
;(set-face-foreground 'font-lock-preprocessor-face "#e5786d")
;(set-face-foreground 'font-lock-negation-char-face "#e7f6da")
;(set-face-foreground 'link "#8ac6f2")
;(set-face-bold-p 'link t)
;(set-face-underline-p 'link t)

;(set-face-foreground 'show-paren-match "#f6f3e8")
;(set-face-background 'show-paren-match "#857b6f")
;(set-face-bold-p 'show-paren-match t)

;(set-face-foreground 'region "#f6f3e8")
;(set-face-background 'region "#444444")
;(set-face-foreground 'lazy-highlight "black")
;(set-face-background 'lazy-highlight "yellow")

