---

- name: Update homebrew
  command: "brew update"
  tags:
    - large_apps
    - brew
    - brew-cask
    - update

- name: Install brew taps
  command: >
    brew tap homebrew/cask-versions
  # brew tap burntsushi/ripgrep https://github.com/BurntSushi/ripgrep.git
  tags:
    - large_apps
    - brew
    - brew-tap


- name: Install brew cask applications
  # command: "brew cask install {{item.install_options | default('') }} {{ item.name }}"
  # TODO: Figure out "Error no cask hydra" issue
  homebrew_cask:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    install_options: "appdir=/Applications,{{ item.install_options | default('') }}"
  with_items: "{{ brew_cask_applications }}"
  ignore_errors: True
  tags:
    - large_apps
    - brew
    - brew-cask


- name: Cleanup homebrew
  command: "brew cleanup -s"
  ignore_errors: True
  tags:
    - large_apps
    - brew
    - cleanup

- name: Cleanup cask
  command: "brew cask cleanup"
  ignore_errors: True
  tags:
    - large_apps
    - brew
    - brew-cask
    - cleanup

- include: app_shortcuts.yml
  tags: shortcuts
