---
- name: Install database packages
  homebrew:
    name: "{{ item.name }}"
    install_options: "{{ item.install_options | default('') }}"
    state: latest
  with_items: "{{ databases_brew_packages }}"
  tags:
    - databases
    - brew
